services:
  - type: web
    name: news-assistant
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn bot_config_panel.app:app --host 0.0.0.0 --port 10000 & python news_assistant_ready/bot.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
